load balancer: http://127.0.0.1:8000
    load balancer address

algorithm: round_robin
    load balancer algorithm

servers: http://127.0.0.1:3000, http://127.0.0.1:3001, http://127.0.0.1:3002, http://127.0.0.1:3003
    server address

weights: 20, 30, 10, 40
    server weights

max connections: 1000, 1000, 1000, 1000
    max server connections

timeout: 10000
    max server response time (ms)

max retries: 1
    max retires
